### PR TITLE
Include option to upload only new files

### LINKED ISSUE #12: FTP only files that are newer or have changed
I know this might be a long shot. But I want to have the ability to only FTPS files that have changed or are new. I think there are flags that you can specify in lftp such as `-Rne`.

Even if you want to point me in the right direction, happy to contribute.

### PR DESCRIPTION
**Pull request by cschlosser**
Add `only_newer` option.

Use like this:
```yml
pipeline:
  deploy:
    image: cschlosser/drone-ftps
    hostname: example.com:21
    secrets: [ ftp_username, ftp_password ]
    only_newer: true
```

This should fix #12

### CODE REVIEW

**Comment by SGTGunner** [comment]
No, neither option worked. It still copies all files.

**Comment by cschlosser** [comment]
Maybe you could give it a try?

**Comment by SGTGunner** [comment]
I tried the -e option as well and no luck.

**Comment by cschlosser** [comment]
Do you have any other idea?

**Comment by SGTGunner** [comment]
Humm, a couple of things to consider perhaps. I notice that you did not use all the flags? There is an issue around the timezone that could also be a problem. There is an option of `--ignore-time` which may help with that.

**Comment by cschlosser** [comment]
I used all the flags. The -R was there before already but maybe it needs to be in this order so I added it twice. Also added the ignore time option

**Comment by SGTGunner** [comment]
Sorry, for the delay. Do I still use the `-e` in the `only_newer:` option?

**Comment by cschlosser** [comment]
The `only_newer: true` results in `-Rne --ignore-time` to be added to the string

**Comment by hussainb** [comment]
I might be late to this post but I was looking at using drone to deploy php projects which do not require a build and only the changed files to be updated using FTP.
This plugin fits the purpose if the only-newer flag works.
by looking at the conversation above, I was just wondering how lftp detects which files are new or modified, maybe by the date-time?

upon reading the drone docs, drone creates a temporary directory and clones the repo which means all the files are always newly created in every build, so can this be the reason that lftp might be uploading all the files again?

**Comment by cschlosser** [comment]
Thanks for the suggestion @hussainb ,

Yes, lftp uses the timestamp of the files to detect what changed.
A git clone keeps the timestamps correctly in sync with the remote repository.
This is not the cause of the problem.

**Comment by hussainb** [comment]
Didn't know that!
Thanks!

**Comment by josevavia** [comment]
If I can help to anyone with my experience, I was able to get this working using `-Rn --ignore-time`

The `-e` was not helpful in my case, because in remote server there are generated file that I dont want to delete in each deploy

**Comment by morvy** [comment]
just tried this PR and I nearly collapsed as after uploading all the files it started with deleting of my whole FTP :D this PR ignored my `PLUGIN_DEST_DIR` and used root. Or does "latest" use `PLUGIN_DEST_DIR` while "only-newer" uses `dest_dir` ?

**Comment by cschlosser** [comment]
This branch is quite out of date.
Did you merge it with master?

**Comment by morvy** [comment]
I only used `.drone.yml` with `cschlosser/drone-ftps:only-newer` .. would be really nice if it worked. Later I found out the FTP was nearly fully deleted but I had a backup so no data loss :)

**Comment by cschlosser** [comment]
The example configuration from the `master` readme no longer matches this branch.
I may be able to take a look at this in the next few days but we had problems getting this to work reliably so I'm not too hopeful right now.

**Comment by cschlosser** [comment]
Should be included in #31, hopefully.

**Pull request closed without merging**
